version: 1

deploy:
  steps:
    setupVariables:
      after: &login-k8s
        - mkdir -p ~/.kube
        - aws eks update-kubeconfig --name $CLUSTER_NAME --region us-west-2  
        - cat namespace.yaml
        - sed 's/!!!USER!!!/'"$USER"'/g' configmap.yml)
        - kubectl config set-context --current --namespace=$NAMESPACE

destroy:
  steps:
    setupVariables:
      after: *login-k8s