version: 1

deploy:
  steps:
    setupVariables:
      after: &login-k8s
        - mkdir -p ~/.kube
        - awsv2 eks update-kubeconfig --name $CLUSTER_NAME --region $REGION 
        - cat ~/.kube/config

destroy:
  steps:
    setupVariables:
      after: *login-k8s