apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUyTlRRd016WXlPRGt3SGhjTk1qSXdOVE14TWpJek1USTVXaGNOTXpJd05USTRNakl6TVRJNQpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUyTlRRd016WXlPRGt3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTV0JzcWl2TUd2V2QxLyt4eGRJR3NDc3crMG4zZVpDUXhtelQwUDBEWWMKejJBK2p5VmtockhsM1ZLbGpEVkVDVzRVajcvaG8yM2R6VHFVdXhpY1pOYndvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVhNWUMva0lDKzhwVmZxOWJ0UjFpCnlFMXlaRGt3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnWWFCbXFOMWJ4eWRINENmS1hPbzVQR1FYM2dMYTZnOXoKaXp5eFhNTkpUWjhDSVFDL2d2a1p1Y0EyaXJjQjl3NGdNMmJkTERnTVJtRjh2cXpKRkZRZi84dm1EQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://54.188.178.51:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjNVNWpJYlRjWjhwVEJxaEkyNkotYW03MWFiX0xybmF0dThkcjhRaHlXbUUifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InJlbW90ZS1hZG1pbi10b2tlbi16bmg1NCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJyZW1vdGUtYWRtaW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiIxOGYyZDYwYS0yMDY3LTQ2MTktODBlZS01MTU1NDBiYTI4YWIiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVmYXVsdDpyZW1vdGUtYWRtaW4ifQ.Xxs-xlBAnajKdwUgjD_EmtHTl9L_HqPoUXMJPVJws8odEikVkvsKAe69gqUinCOF-ADS2yeg4Vqa4FeBzFJaXazSPg6xsUH3GFFbAufQwO5YeUr2hw7-jKNvzwYGMIx-KKHn13DdsRwXkN1vunqxgdnTNBfBJGLiA_DAg4T8po6x3tbcf3GEiWUFZjPJafLCgx9UCWaKtg_7NVk_z5qNN0FJNOwBLJ4GjWAep2063W1PyoedALmohjUJTeBy8r1FtoYgEjgnKmDLpVC0VZS8BvZMSFrq_nO5eIX5ll94CYL_AscYKtlK-6cIdr-dFonbwAFo6NOm7w8ttQSxF4PpGQ