version: 1

deploy:
  steps:
    setupVariables:
      after: &login-k8s
        - mkdir -p ~/.kube
        - echo $KUBE_CONFIG > ~/.kube/config
        - cat ~/.kube/config
        - echo "$(sed 's/!!!NAMESPACE!!!/'"$NAMESPACE"'/g' namespace.yaml)" > namespace.yaml;
        - cat namespace.yaml

destroy:
  steps:
    setupVariables:
      after: *login-k8s