version: 1

deploy:
  steps:
    setupVariables:
      after: &login-k8s
        - mkdir -p ~/.kube
        - aws s3 cp s3://acme-demo-tfstate-dev/acme-fitness.yaml acme-fitness.yaml
        - cp acme-fitness.yaml ~/.kube/config
        - cat ~/.kube/config
        - echo "$(sed 's/!!!NAMESPACE!!!/'"$NAMESPACE"'/g' namespace.yaml)" > namespace.yaml;
        - cat namespace.yaml

destroy:
  steps:
    setupVariables:
      after: *login-k8s